# Generated by Django 2.2.5 on 2020-12-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otomobil', '0002_auto_20201220_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kira',
            name='rezdate',
            field=models.DateTimeField(),
        ),
    ]
