# Generated by Django 2.2.5 on 2020-12-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otomobil', '0003_auto_20201220_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kira',
            name='returntime',
        ),
        migrations.RemoveField(
            model_name='kira',
            name='reztime',
        ),
        migrations.AlterField(
            model_name='kira',
            name='returndate',
            field=models.DateTimeField(),
        ),
    ]
