# Generated by Django 2.2.5 on 2020-12-20 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otomobil', '0004_auto_20201220_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kira',
            name='days',
        ),
        migrations.RemoveField(
            model_name='kira',
            name='price',
        ),
        migrations.RemoveField(
            model_name='kira',
            name='total',
        ),
    ]
