# Generated by Django 2.2.5 on 2020-12-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otomobil', '0005_auto_20201220_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='kira',
            name='days',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kira',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
