# Generated by Django 2.2.5 on 2020-12-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otomobil', '0006_auto_20201220_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kira',
            name='days',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='kira',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
