# Generated by Django 2.2.5 on 2020-12-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otomobil', '0008_remove_kira_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='kira',
            name='days',
            field=models.IntegerField(default=0),
        ),
    ]
