# Generated by Django 2.2.5 on 2020-12-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otomobil', '0009_kira_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='otomobil',
            name='fuel',
            field=models.CharField(choices=[('Benzin', 'Benzin'), ('Dizel', 'Dizel'), ('Lpg', 'Lpg')], default='Benzin', max_length=10),
        ),
        migrations.AddField(
            model_name='otomobil',
            name='gear',
            field=models.CharField(choices=[('Duz', 'Düz'), ('Otomatik', 'Otomatik'), ('Triptonik', 'Triptonik')], default='Duz', max_length=10),
        ),
    ]
