# Generated by Django 2.2.5 on 2020-12-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otomobil', '0011_auto_20201221_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otomobil',
            name='daily_km',
            field=models.IntegerField(choices=[(250, '250 Km'), (500, '500 Km'), (750, '750 Km'), (1000, '1000 Km'), (1250, '1250 Km'), (1500, '1500 Km')], default=250),
        ),
    ]
