# Generated by Django 2.2.5 on 2020-12-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otomobil', '0012_auto_20201221_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kira',
            name='create_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='kira',
            name='returndate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='kira',
            name='rezdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='kira',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
    ]
